#name = (self.input1, self.input2, self.input3, self.input4, self.input5, self.input6, self.input7, self.input8, self.input9, self.input10, self.input11, self.input12)
name1 = ["self.input1", "self.input2", "self.input3", "self.input4", "self.input5", "self.input6", "self.input7", "self.input8", "self.input9", "self.input10", "self.input11", "self.input12"]
print name1[1]

		"""
		self.input1 = QtGui.QLineEdit(self)
		self.input1.returnPressed.connect(self.apply_clicked)
		grid.addWidget(self.input1, 0, 1)
		self.input2 = QtGui.QLineEdit(self)
		self.input2.returnPressed.connect(self.apply_clicked)
		grid.addWidget(self.input2, 0, 2)
		self.input3 = QtGui.QLineEdit(self)
		self.input3.returnPressed.connect(self.apply_clicked)
		grid.addWidget(self.input3, 0, 3)
		self.input4 = QtGui.QLineEdit(self)
		self.input4.returnPressed.connect(self.apply_clicked)
		grid.addWidget(self.input4, 0, 4)
		self.input5 = QtGui.QLineEdit(self)
		self.input5.returnPressed.connect(self.apply_clicked)
		grid.addWidget(self.input5, 1, 1)
		self.input6 = QtGui.QLineEdit(self)
		self.input6.returnPressed.connect(self.apply_clicked)
		grid.addWidget(self.input6, 1, 2)
		self.input7 = QtGui.QLineEdit(self)
		self.input7.returnPressed.connect(self.apply_clicked)
		grid.addWidget(self.input7, 1, 3)
		self.input8 = QtGui.QLineEdit(self)
		self.input8.returnPressed.connect(self.apply_clicked)
		grid.addWidget(self.input8, 1, 4)
		self.input9 = QtGui.QLineEdit(self)
		self.input9.returnPressed.connect(self.apply_clicked)
		grid.addWidget(self.input9, 2, 1)
		self.input10 = QtGui.QLineEdit(self)
		self.input10.returnPressed.connect(self.apply_clicked)
		grid.addWidget(self.input10, 2, 2)
		self.input11 = QtGui.QLineEdit(self)
		self.input11.returnPressed.connect(self.apply_clicked)
		grid.addWidget(self.input11, 2, 3)
		self.input12 = QtGui.QLineEdit(self)
		self.input12.returnPressed.connect(self.apply_clicked)
		grid.addWidget(self.input12, 2, 4)
		"""